-- 7/14/2022 Added Company ID and Company Name
-- 8/19/2022 Added the trim in the select and the CPC.PLAN_YEAR = 2023

SELECT
COMP.COMPANY_ID
,TRIM(UPPER(REGEXP_REPLACE(COMP.NAME,'[^a-zA-Z ]',''))) AS "NAME"
,PS.PAY_GROUP_ID
,PS.PR_CYCLE_NUMBER AS "Pay Period"
,PS.FIRST_DATE AS "Pay Period Begin Date"
,PS.INVESTMENT_DATE AS "Pay Period End Date"
,PS.LAST_DATE AS "Deduction Cutoff Date"
,PS.CUTOFF_DATE AS "File Run Date"
,PS.EXC_STANDARD
,PS.SUPP_CYCLE_NO

FROM PAYROLL_SCHEDULE PS

INNER JOIN COMPANY_PAYROLL_CONFIG_DETAIL CPCG
ON PS.PAY_GROUP_ID = CPCG.PAY_GROUP_ID
AND PS.PR_SCHEDULE_YEAR = CPCG.PLAN_YEAR

INNER JOIN COMPANY COMP
ON COMP.COMPANY_ID = CPCG.COMPANY_ID
AND COMP.ASSOCIATION_ID IS NULL
AND COMP.COMPANY_ID NOT IN('31652','31667','31687','31688','31725')
AND UPPER(COMP.NAME) NOT LIKE '%TEST%'

INNER JOIN COMPANY_DETAIL CD
ON CD.COMPANY_ID = COMP.COMPANY_ID
AND CD.TEST_COMPANY_IND = 'N'

WHERE PS.PR_SCHEDULE_YEAR = '2024'

ORDER BY PS.PAY_GROUP_ID,PS.PR_CYCLE_NUMBER;