SELECT CD.COMPANY_ID
,CD.MERCER_ONECODE
,PC.OG_FUTURE_DATED_EVENTS_IND
,CASE WHEN CPD.YEAR_BEGIN_DATE IS NULL THEN '01-JAN-24' ELSE TO_CHAR(CPD.YEAR_BEGIN_DATE) END AS "YEAR_BEGIN_DATE"
,CASE WHEN CPD.YEAR_END_DATE IS NULL THEN '31-DEC-24' ELSE TO_CHAR(CPD.YEAR_END_DATE) END AS "YEAR_END_DATE"

FROM COMPANY_DETAIL CD

INNER JOIN COMPANY_PLAN_DETAIL CPD
ON CD.COMPANY_ID = CPD.COMPANY_ID
AND CPD.PLAN_YEAR = 2024

LEFT JOIN PAYAUTO_PAYROLL_CONFIG PC
ON PC.MERCER_ONECODE = CD.MERCER_ONECODE
AND PC.PLAN_YEAR = 2024;